In [81]:
#Importando biblioteca para trabalhar
import pandas as pd
import numpy as np 

mes = 'dez'
df_mes = pd.read_csv('pag-'+ mes + '-2020.csv', encoding='latin-1', decimal=',')
#df_mes = df_mes.drop(['Unnamed: 7'], axis=1)
df_mes.head()

FileNotFoundError: [Errno 2] No such file or directory: 'pag-dez-2020.csv'

In [75]:


df_mes['Salário Base'] = df_mes['Salário Base'].apply(lambda x: x.split('R$')[1])
df_mes['Salário Vantagens'] = df_mes['Salário Vantagens'].apply(lambda x: x.split('R$')[1])
df_mes['Salário Gratificação'] = df_mes['Salário Gratificação'].apply(lambda x: x.split('R$')[1])

df_mes['Salário Base'] = df_mes['Salário Base'].apply(lambda x: x.split()[0].replace('.', ''))
df_mes['Salário Vantagens'] = df_mes['Salário Vantagens'].apply(lambda x: x.split()[0].replace('.', ''))
df_mes['Salário Gratificação'] = df_mes['Salário Gratificação'].apply(lambda x: x.split()[0].replace('.', ''))

df_mes['Salário Base'] = df_mes['Salário Base'].str.replace(',', '.').astype(float)
df_mes['Salário Vantagens'] = df_mes['Salário Vantagens'].str.replace(',', '.').astype(float)
df_mes['Salário Gratificação'] = df_mes['Salário Gratificação'].str.replace(',', '.').astype(float)

lista_colunas_sum = ['Salário Base', 'Salário Vantagens', 'Salário Gratificação']
df_mes['Valor Recebido'] = df_mes.loc[:,lista_colunas_sum].sum(axis=1)
df_mes.head()

,Nome,Matrícula,Tipo Servidor,Cargo,Salário Base,Salário Vantagens,Salário Gratificação,Valor Recebido
0,ABIGAIL DONATA ALVES,1951,Cargo Efetivo/ Estatutário,AGENTE COMUNITÁRIO DE SAÚDE,1400.00,420.00,0.00,1820.00
1,ABIGAIL OLIVEIRA DOS SANTOS SANTANA,9929,Cargo Efetivo/ Estatutário,AGENTE DE LIMPEZA,1045.00,104.50,0.00,1149.50
2,ABRAHAO SILVA MAIA,8063,Cargo Efetivo/ Estatutário,GUARDA MUNICIPAL,1177.39,353.22,529.83,2060.44
3,ADAILTON ANDRADE DE SOUZA,2135,Cargo Efetivo/ Estatutário,GUARDA MUNICIPAL,1177.39,176.61,529.83,1883.83
4,ADAILTON CAVALCANTE DE MOURA,10651,Cargo Efetivo/ Estatutário,GUARDA MUNICIPAL,1177.39,294.35,470.96,1942.70

In [76]:
df_mes.insert(loc=3, 
             column = 'Mês',
             value = 'novembro')

df_mes.head()

,Nome,Matrícula,Tipo Servidor,Mês,Cargo,Salário Base,Salário Vantagens,Salário Gratificação,Valor Recebido
0,ABIGAIL DONATA ALVES,1951,Cargo Efetivo/ Estatutário,novembro,AGENTE COMUNITÁRIO DE SAÚDE,1400.00,420.00,0.00,1820.00
1,ABIGAIL OLIVEIRA DOS SANTOS SANTANA,9929,Cargo Efetivo/ Estatutário,novembro,AGENTE DE LIMPEZA,1045.00,104.50,0.00,1149.50
2,ABRAHAO SILVA MAIA,8063,Cargo Efetivo/ Estatutário,novembro,GUARDA MUNICIPAL,1177.39,353.22,529.83,2060.44
3,ADAILTON ANDRADE DE SOUZA,2135,Cargo Efetivo/ Estatutário,novembro,GUARDA MUNICIPAL,1177.39,176.61,529.83,1883.83
4,ADAILTON CAVALCANTE DE MOURA,10651,Cargo Efetivo/ Estatutário,novembro,GUARDA MUNICIPAL,1177.39,294.35,470.96,1942.70

In [77]:
df_mes.insert(loc=4, 
             column = 'Ano',
             value = '2020')

df_mes.head()

,Nome,Matrícula,Tipo Servidor,Mês,Ano,Cargo,Salário Base,Salário Vantagens,Salário Gratificação,Valor Recebido
0,ABIGAIL DONATA ALVES,1951,Cargo Efetivo/ Estatutário,novembro,2020,AGENTE COMUNITÁRIO DE SAÚDE,1400.00,420.00,0.00,1820.00
1,ABIGAIL OLIVEIRA DOS SANTOS SANTANA,9929,Cargo Efetivo/ Estatutário,novembro,2020,AGENTE DE LIMPEZA,1045.00,104.50,0.00,1149.50
2,ABRAHAO SILVA MAIA,8063,Cargo Efetivo/ Estatutário,novembro,2020,GUARDA MUNICIPAL,1177.39,353.22,529.83,2060.44
3,ADAILTON ANDRADE DE SOUZA,2135,Cargo Efetivo/ Estatutário,novembro,2020,GUARDA MUNICIPAL,1177.39,176.61,529.83,1883.83
4,ADAILTON CAVALCANTE DE MOURA,10651,Cargo Efetivo/ Estatutário,novembro,2020,GUARDA MUNICIPAL,1177.39,294.35,470.96,1942.70

In [78]:
df_mes.to_csv('dados-limpos/' + mes + '-2020-limpo.csv', index=False, encoding='utf-8')

In [79]:
df = pd.read_csv('dados-limpos/' + mes + '-2020-limpo.csv')
df.head()

,Nome,Matrícula,Tipo Servidor,Mês,Ano,Cargo,Salário Base,Salário Vantagens,Salário Gratificação,Valor Recebido
0,ABIGAIL DONATA ALVES,1951,Cargo Efetivo/ Estatutário,novembro,2020,AGENTE COMUNITÁRIO DE SAÚDE,1400.00,420.00,0.00,1820.00
1,ABIGAIL OLIVEIRA DOS SANTOS SANTANA,9929,Cargo Efetivo/ Estatutário,novembro,2020,AGENTE DE LIMPEZA,1045.00,104.50,0.00,1149.50
2,ABRAHAO SILVA MAIA,8063,Cargo Efetivo/ Estatutário,novembro,2020,GUARDA MUNICIPAL,1177.39,353.22,529.83,2060.44
3,ADAILTON ANDRADE DE SOUZA,2135,Cargo Efetivo/ Estatutário,novembro,2020,GUARDA MUNICIPAL,1177.39,176.61,529.83,1883.83
4,ADAILTON CAVALCANTE DE MOURA,10651,Cargo Efetivo/ Estatutário,novembro,2020,GUARDA MUNICIPAL,1177.39,294.35,470.96,1942.70

In [80]:
import openpyxl
df = pd.read_csv('dados-limpos/' + mes + '-2020-limpo.csv')
df.to_excel('dados-limpos/xlsx/' + mes + '-2020-xlsx.xlsx', index=False, encoding='utf-8')